export function moduleSeverity(value: unknown): string {
  const map: Record<string, string> = {
    new: 'info',
    draft: 'warn',
    active: 'success',
    approved: 'success',
    shipped: 'info',
    delivered: 'success',
    cancelled: 'danger',
    archived: 'danger',
    pending: 'warn',
    completed: 'success',
    true: 'info',
    false: 'secondary',
    raw_materials: 'info',
    production: 'warn',
    finished_goods: 'success',
    call: 'info',
    email: 'warn',
    meeting: 'success',
    note: 'secondary',
    system: 'contrast',
    receipt: 'success',
    write_off: 'danger',
    transfer_in: 'info',
    transfer_out: 'warn',
    material: 'info',
    labor: 'warn',
    overhead: 'secondary',
    torg12: 'info',
    ttn: 'warn',
    invoice: 'success',
    in_progress: 'warn',
    kp_sent: 'info',
    won: 'success',
    lost: 'danger',
    Резерв: 'warn',
    'В работе': 'info',
    Выполнено: 'success',
    Отменён: 'danger',
    Черновик: 'warn',
  };
  const key = typeof value === 'string' ? value : String(value);
  return map[key] ?? 'info';
}
