export type { IProduct, ProductKind } from './product.interface';
export type { ICategory } from './category.interface';
export type { ICounterparty, CounterpartyLegalForm, CounterpartyRole } from './counterparty.interface';
export type { IUser, UserRole } from './user.interface';
export type { IRole } from './role.interface';
export type { IEntityStatus } from './entity-status.interface';
export type { IWorkType } from './work-type.interface';
export type { ISetting } from './setting.interface';
export type { IQuotation } from './quotation.interface';
export type { IOrder } from './order.interface';
export type { IBom } from './bom.interface';
export type { IOperation } from './operation.interface';
export type { ITechProcess } from './techProcess.interface';
export type { IPurchaseRequest } from './purchaseRequest.interface';
export type { IPurchaseOrder } from './purchaseOrder.interface';
export type { IWarehouse } from './warehouse.interface';
export type { IStockMovement } from './stockMovement.interface';
export type { IReservation } from './reservation.interface';
export type { IWorkOrder } from './workOrder.interface';
export type { IWorkOrderOperation } from './workOrderOperation.interface';
export type { ICostCalculation } from './costCalculation.interface';
export type { IActualCost } from './actualCost.interface';
export type { IShipment } from './shipment.interface';
export type { IShippingDoc } from './shippingDoc.interface';
export type { IInteraction } from './interaction.interface';
export type { ICounter } from './counter.interface';
export type { IQuotationItem } from './quotationItem.interface';
export type { IDocumentTemplate, IDocumentBlock, DocumentBlockType, DocType } from './documentTemplate.interface';
export type { ITender } from './tender.interface';
export type { IProductPassport } from './productPassport.interface';
export type { IComplianceRule, IComplianceCheck, IComplianceBatchResult, IComplianceSummary, ComplianceOperator, ComplianceSeverity } from './compliance.interface';
export type { IAttributeDefinition, AttributeType } from './attributeDefinition.interface';
export type { IEntityAttributeValue } from './entityAttributeValue.interface';
